package utils.error;

public enum ErrorType {
    ADD_CHILD_TO_NOTHING,
    ADD_CHILD_TO_SLIDE,
    DELETE_WORKSPACE,
    EMPTY_NAME,
    NAME_ALREADY_EXISTS,
    NO_DELETABLE_NODE_SELECTED,
    NO_PRESENTATION_SELECTED,
    NO_PROJECT_SELECTED,
    NOT_EMPTY_NODE,
    OPEN_FILE,
    SAVE_FILE,
    UNDEFINED
}
